### ISSUE TITLE
Query string is not properly urlencoded

### ISSUE THREAD

**Issue by jukkaho** [teracow/googliser#1]
Query string needs urlencoding for some other symbols in addition to space. For example single quotes (') in query break passing parameters to wget.

A sample way to fix this can be found from here: http://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command (see second solution with pure BASH) which can replace current "tr"-based implementation. Note that sample processes only the first parameter instead of all of them.

**Comment by teracow** [comment]
Hi jukkaho and thank you for your feedback.

This is probably the result of my choice to use **getopt** for argument parsing. But I suspect that the problem you've found will be an issue with _any_ argument parsing using the CLI. 

Inevitably, there will need to be characters to surround the search query (quotes). Which become a problem when someone wants a query that includes quotes. So, these need be escaped. Then someone else wants a query with quotes AND escape characters. And so on ... :)

"_Shell code portability generally goes to 100% as development time goes to infinity._" - [l0b0](http://unix.stackexchange.com/questions/62950/getopt-getopts-or-manual-parsing-what-to-use-when-i-want-to-support-both-shor)

I think it's safe to say that it's infeasible to program for every combination of characters that may be provided as an argument to this script. The urlencode solution is a great idea (and I'll certainly keep it in mind), but the problem of how to handle any character as a script argument needs to be addressed first.

Do you have any thoughts on how to solve this without restricting the availability of platforms?

**Comment by jukkaho** [comment]
Sorry but I'm not that great with shell code. Otherwise I would have offered a pull request instead. :) 

I don't think your getopt is broken at all. The problem appears on the line where wget is called as it uses single quotes and query string is embedded there.

I have tested the case with single quotes and a fix similar to what I linked to, though and it works perfectly. As ' is converted to %27, it does not cause problems when calling wget any more. In addition, urlencoding will fix any problems with any other characters like & that might break query strings unintentionally.

**Comment by teracow** [comment]
Cool! Thanks for testing this. :)

I think you're right. But might be worth mentioning here that BASH interprets single quotes differently to double quotes. 

I've changed the single quotes to double quotes for the **wget** query string, tested it with the query "_Schrödinger's cat_", and (so far) it appears to be working correctly. 

I'll perform some more tests and push a fix shortly.

**Comment by teracow** [comment]
New version now available. Can you please test this one out and let me know how it goes?

Thanks.

**Comment by jukkaho** [comment]
This seems to work with single quote characters at least. I'm going to close this issue for now as that seems to fix the most important part. I would still recommend implementing a generic urlencoding in the future.

Thanks.
