### ISSUE TITLE
couldn't download Google search results

### ISSUE THREAD

**Issue by rayjs** [teracow/googliser#14]
Thank you for writing and sharing this very helpful script.
I had previously used this script few months back, it worked fine.

But now, no matter what phrase I use, I always get this error. I am using your latest script. Please help

`./googliser.sh -p "cats"`

` googliser.sh - 2017-12-17 PID:[26406]

 -> processing query: "cats"
 -> searching Google: 0/10 result groups downloaded. No results!
 !! couldn't download Google search results

 -> All done! (with errors)
`

**Comment by teracow** [comment]
Hey @rayjs. :)

Can you please run your search query again with the `--debug` option? If it fails, please post the debug log back here.

As per the readme: 

> If selected, debugging output is appended to 'debug.log' in the image sub-directory. This file is always created in the temporary build directory. Great for finding out what external commands and parameters were used!

**Comment by rayjs** [comment]
Hi @teracow ,

Somehow, its working now, I just ran the latest script again. It wasnt the script then, perhaps the google was refusing requests or something.

Nevertheless, thank you again for the script and the response.

 -> searching Google: 10/10 result groups downloaded. 761 results!
 -> acquiring images: 569/761 downloaded and 192/761 failed. (25%) Ran out of images to download!

 -> All done! (with errors)

**Comment by teracow** [comment]
It happens sometimes. Network difficulties can temporarily mean no results. ;)

**Comment by tsitsu1** [comment]
hi i'm using googliser several months now and i find it extremely helpful. in the last few days it just not working. i tried it if few computers and in different locations, the internet connection work fine and google search work ok. i uses this command: ./googliser.sh -p "kittens" -T 'Kittens!' -f0 -SC -n200
and get this error: searching Google: 10/10 result groups downloaded: (no results!)
any help would be appreciated. thx

**Comment by teracow** [comment]
> in the last few days it just not working.

Sorry, please check issue #96 for more information.
