### ISSUE TITLE
Linking the output image-name and the download.links.list

### ISSUE THREAD

**Issue by rayjs** [teracow/googliser#15]
Hi again,

I have two questions:
a) I was wondering if it is possible to link the line number in `download.links.list` file and the saved image name. For e.g the image name can correspond to the line num in `download.links.list` file. The other way round is to redownload with the `download.links.list` file and establish the correspondence, but this would involve downloading twice.

b) I noticed even with the `-s` flag **sometimes** I do not have `download.links.list` file in the img sub dir. Any known reasons?

**Comment by rayjs** [comment]
I just checked I think there is one-to-one correspondence in the image index number and the  `download.links.list` file. So please scratch that question.

However even with the -s flag I do not get the  `download.links.list` file.

Here is my command: 
`./googliser.sh -p "$line" --type photo -n 350 -r 5 -s -m vga -o /path/to/folder/"$line" -P 10 -N`

**Comment by rayjs** [comment]
So it seems whenever the script cannot download X number of images as specified by the argument `-n X` it does not write the `download.links.list` file.

**Comment by rayjs** [comment]
It works now after commenting out the following if condition:
https://github.com/teracow/googliser/blob/master/googliser.sh#L891

**Comment by teracow** [comment]
Hey @rayjs. :)

Good pickup. You found a set of conditions I hadn't planned on or tested for. 

I'll change that line so it will copy the links even if the downloader runs out of images. 

Thanks!

**Comment by teracow** [comment]
Also, I noticed you're using a variable called `$line` for your phrase. You might be interested in a feature I added a while back to read a list of phrases from file. Check out the `-i` or `--input` parameter.

**Comment by rayjs** [comment]
Did not know that. Thank you!
