### ISSUE TITLE
No Results! after about 100 loops

### ISSUE THREAD

**Issue by sad-and-desperate** [teracow/googliser#17]
I'm attempting your (marvelous) script over 1000 times, but after about a hundred loops, I get the "No Results!" message for every subsequent search in the loop. Afterwards, googliser shows "No Results!" for any future searches.

 I currently cannot use googliser at all as I ran it through the loop, and I'm not sure how to reset it. Restarting my computer does not reset it, but it has been reset before and I don't know why.

**Comment by teracow** [comment]
Have you tried from another IP address? Google might have temporarily blocked you due to excessive requests. ;)

**Comment by teracow** [comment]
BTW: here's some info about how-and-why Google can ban you: [Preventing bans](https://ghostproxies.com/blog/preventing-bans-captcha-google)

**Comment by sad-and-desperate** [comment]
<3

**Comment by teracow** [comment]
Are your Google searches working again?

**Comment by sad-and-desperate** [comment]
It stopped working completely on my computer actually. I get no results no matter where I am. I've been checking every day for the last few days

**Comment by teracow** [comment]
Did you download the latest version? Google changed their page-code about [4 days ago](https://github.com/teracow/googliser/issues/18) and I pushed a [commit](https://github.com/teracow/googliser/commit/57eb2df8b83584045fb7658be57d712ffedb72a4) to fix this.

**Comment by sad-and-desperate** [comment]
I got the update; it works. And I'm positive that my IP was being blocked. I will take things a little slower so I dont get banned, which works perfectly fine for my purposes. Thank's a lot for the info

**Comment by teracow** [comment]
No worries. :)
