### ISSUE TITLE
script never ending

### ISSUE THREAD

**Issue by simdax** [teracow/googliser#2]
Hello !

The script looks great, but I can't achieve downloading one image. The script just begins, and do... nothing

googliser.sh - v1.23 (2016-09-12) PID:[2653]
 -> searching Google: 0/10 result groups downloaded. 

I have to stop it myself

I'm on manjaro linux. Do we have to enable something on google or something ?

Cheers

**Comment by teracow** [comment]
Hi simdax - Happy New Year!

Thanks for reporting this problem. I've not used Manjaro myself, but had hoped to try it out one day. This might be the day. :)

Can you please upload the session debug log file? It's generated automatically and will be in **/dev/shm/googliser.[PID].[UNIQ]/debug.log**

The PID is shown when the script runs, and UNIQ could be any 3 letter code.

**Comment by simdax** [comment]
oh cool, I love this /dev things :)

I let the program run for something like one minute : 

```
> started: 'mer. janv.  4 10:28:43 CET 2017'
? $script_details: 'googliser.sh - v1.23 (2016-09-12) PID:[3964]'
? $user_parameters_raw: '-p castle'
= environment: '*** decoded user parameters ***'
? $user_query: 'castle'
? $images_required: '25'
? $fail_limit: '40'
? $parallel_limit: '8'
? $timeout: '15'
? $retries: '3'
? $upper_size_limit: '0'
? $lower_size_limit: '1000'
? $create_gallery: 'true'
? $gallery_title: ''
? $links: 'false'
? $colour: 'false'
? $verbose: 'true'
? $debug: 'false'
? $skip_no_size: 'false'
? $remove_after: 'false'
= environment: '*** internal parameters ***'
? $google_max: '1000'
? $temp_path: '/dev/shm/googliser.3964.Oke'
$ required program is available: 'wget'
$ required program is available: 'montage'
$ required program is available: 'convert'
$ optional program is available: 'identify'
? $safe_query: 'castle'
? $target_path: '/dev/shm/googliser.3864.RCa/castle'
~ $gallery_title was unspecified so set as: 'castle'
$ create sub-directory [/dev/shm/googliser.3864.RCa/castle]: 'success!'
~ $max_results_required too low so set as $images_required + $fail_limit: '65'
\ [DownloadResultGroups]: 'entry'
- result group (00) download: 'start'
? result group (00) $wget_list_cmd: 'wget --quiet "https://www.google.com.au/search?&tbm=isch&nfpr=1&q=castle&hl=en&site=imghp&ijn=0&start=0" --user-agent 'Mozilla/5.0 (X11; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0' --output-document "/dev/shm/googliser.3964.Oke/results.page.html.0"'
! [SIGINT]: 'detected'
< finished: 'mer. janv.  4 10:29:29 CET 2017'

```

**Comment by teracow** [comment]
I knew that debug log would come in handy one day. :)

And I've only just realised that I forgot to include **timeout** and **retry** values when running the initial search. I'll include those now. But that's not the reason the search results are not downloading.

Can you please run these commands to verify that wget is able to download at your end? 

`wget --timeout=15 --tries=3 "https://www.google.com" --output-document "search.page.html"`

and if that works, then please try:

`wget --timeout=15 --tries=3 "https://www.google.com/search?&tbm=isch&nfpr=1&q=castle&hl=en&site=imghp&ijn=0&start=0" --user-agent 'Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0' --output-document "results.page.html"`

This runs wget with verbose output, so hopefully we can see what's going on there.

**Comment by simdax** [comment]
```
wget --timeout=15 --tries=3 "https://www.google.com" --output-document "search.page.html"
--2017-01-05 11:18:13--  https://www.google.com/
Résolution de www.google.com (www.google.com)… 2a00:1450:4006:803::2004, 216.58.210.196
Connexion à www.google.com (www.google.com)|2a00:1450:4006:803::2004|:443… échec : Connexion terminée par expiration du délai d'attente.
Connexion à www.google.com (www.google.com)|216.58.210.196|:443… connecté.
requête HTTP transmise, en attente de la réponse… 302 Found
Emplacement : https://www.google.fr/?gfe_rd=cr&ei=Zg9uWPnTNrGs8wfDgoqABA [suivant]
--2017-01-05 11:18:28--  https://www.google.fr/?gfe_rd=cr&ei=Zg9uWPnTNrGs8wfDgoqABA
Résolution de www.google.fr (www.google.fr)… 2a00:1450:4006:803::2003, 216.58.210.195
Connexion à www.google.fr (www.google.fr)|2a00:1450:4006:803::2003|:443… échec : Connexion terminée par expiration du délai d'attente.
Connexion à www.google.fr (www.google.fr)|216.58.210.195|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : non indiqué [text/html]
Sauvegarde en : « search.page.html »

search.page.html                       [ <=>                                                             ]  10,02K  --.-KB/s    in 0,001s  

2017-01-05 11:18:43 (12,9 MB/s) - « search.page.html » sauvegardé [10264]

===============================

wget --timeout=15 --tries=3 "https://www.google.com/search?&tbm=isch&nfpr=1&q=castle&hl=en&site=imghp&ijn=0&start=0" --user-agent 'Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0' --output-document "results.page.html"
--2017-01-05 11:19:05--  https://www.google.com/search?&tbm=isch&nfpr=1&q=castle&hl=en&site=imghp&ijn=0&start=0
Résolution de www.google.com (www.google.com)… 2a00:1450:4006:803::2004, 216.58.210.196
Connexion à www.google.com (www.google.com)|2a00:1450:4006:803::2004|:443… échec : Connexion terminée par expiration du délai d'attente.
Connexion à www.google.com (www.google.com)|216.58.210.196|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : non indiqué [text/javascript]
Sauvegarde en : « results.page.html »

results.page.html                      [ <=>                                                             ] 120,06K  --.-KB/s    in 0,04s   

2017-01-05 11:19:20 (2,71 MB/s) - « results.page.html » sauvegardé [122939]

```

I don't know if it is related, but this time my manjaro must wait for a long time before internet wakes up. it finally did the thing but not instantaneously.  maybe it's a hint ??

**Comment by teracow** [comment]
You're right - it may be a hint. ;) 

Both of those wget commands experienced timeouts, but were successful after retrying. Looks like your internet may be a bit slow. Are you using a VPN? Slow DNS?

I've just updated the main script to include **timeout** and **retry** values for the initial Google results search. Can you please perform a `git pull` and try running the script again?

**Comment by simdax** [comment]
ok it works :)
I just had to wait. Cool that it served to improve the script

thanks !

**Comment by teracow** [comment]
It **did** improve the script. :)

Thank you.
