### ISSUE TITLE
macOS 10.14.0 compatible

### ISSUE THREAD

**Issue by niXta1** [teracow/googliser#22]
It works fine on macOS 10.14.0. I've only used it with --no-gallery.

But I do get:
`googliser.sh: line 1155: 9255/0: division by 0 (error token is "0")`

**Comment by teracow** [comment]
Nice catch. I think I can see why this could happen. 

Can you please post the debug log for this session? Or else, if you can please make this error occur again and post your debug log, that would help a lot.

**Comment by niXta1** [comment]
I had a look at the log and since I only download 1 image and sometimes it takes less than 1s (ie. 0s), therefore the bytes/s is producing an error. :)

**Comment by teracow** [comment]
Agree, I think that's likely the issue. Can you please post the debug log?

**Comment by teracow** [comment]
Hiya @niXta1 I've made a guess at fixing this, can you please download the latest script version and test it for me?

**Comment by niXta1** [comment]
I've inserted 
```
        if [[ $download_seconds -lt 1 ]]; then
            download_seconds=1
            DebugThis '~ $download_seconds too low so set to usable minimum' "$download_seconds"
        fi
```
on row 1153 in the script and so far, no errors. So it looks alright.

**Comment by teracow** [comment]
Thank you for reporting and testing this.
