### ISSUE TITLE
"Too many failures" with latest googliser

### ISSUE THREAD

**Issue by yoiang** [teracow/googliser#29]
Hello!
I'm excited to use your tool!

Running it on macOS 10.14.6 I get the following no matter what search term I use:

```sh
❯ ./googliser.sh --phrase "[[[[my search term]]]]]" --upper-size 100000 --lower-size 2000 -n 600
 googliser.sh v:190811 PID:31578

 -> processing query: "[[[[my search term]]]]]"
 -> searching Google: 10/10 result groups downloaded: (640 results)
 -> acquiring images: 0/600 downloaded and 45/40 failed: (100%) Too many failures!
 -> building gallery: failed!

 !! unable to build thumbnail gallery

 -> All done! (with errors)
```

Let me know whatever else would be useful information to share, if there is a verbose mode or a log or what have you!

**Comment by teracow** [comment]
Hi Ian.

Can you please run a search for a family-friendly term and include the parameter to generate a debug log `--debug`, then post that same debug log?

**Comment by yoiang** [comment]
Hey Dan, my pleasure!

With a little anonymization: [debug.log](https://github.com/teracow/googliser/files/3532787/debug.log)

**Comment by teracow** [comment]
Good work. :)

It looks like the script is not playing well with your ImageMagick `identify` binary. It's not liking any of the image types returned. :(

Can you try to manually download a specific image (let's pick one we can both see):
```
wget --max-redirect 0 --no-check-certificate --timeout 8 --tries 4 --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0" --output-document "/tmp/google-image(test).jpg" "http://www.shannontlkearns.com/wp-content/uploads/2016/06/family-friendly.jpg"
```
Now, let's see what your `identify` binary returns for this file type:
```
echo $(identify -format "%m" /tmp/google-image\(test\).jpg)
```

**Comment by yoiang** [comment]
Oh interesting:
I had this response from `ImageMagick`:

`identify: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/509.`

...and tracked it down to a user level installation of whose purpose I can't remember, removing it in favor for the system level (brew installed) copy fixed the issue, thank you very much!

I apologize for missing the `--debug` parameter in the README, that'll be my first stop next time! I wonder if there is a non-overwhelming way to collect the actual types of errors that occur and surface that to the user rather than just what number and percent failed.

**Comment by teracow** [comment]
Glad you found the problem. :)

I like the idea of collecting the quantity and types of errors. I'll add that to my todo list so it will be included during the next development cycle.

**Comment by teracow** [comment]
Hi @yoiang, I'm revisiting this idea now that I'm coding again. 

Maybe a single indication shown along with the failure rate that displays the download error which occurred most frequently? 

Thoughts please?

**Comment by yoiang** [comment]
Do you find that there are certain classes of errors that occur? I can imagine that happening, if so maybe each one accumulated separately, sorted with the most frequent at the top as you suggested:

```
123) File not found, example: "404 File Not Found image.png"
45) Timeout occurred, example: "DNS reset"
```

or with separated log files?

```
123) File not found - /tmp/googliser/2019-09-12_12-30-10-Z0400_file_not_found.log
45) Timeout occurred - /tmp/googliser/2019-09-12_12-30-10-Z0400_timeout_occured.log
```

**Comment by teracow** [comment]
Some good ideas there Ian. :)

Internal to **googliser**, yes there are a couple of errors that would occur more often than any other. Off the top of my head, out-of-bounds image-size would be the number 1 reason a download fails. Then image type, then we move into the realm of network errors (authentication, file not found, server disconnect, etc...)

Based on your suggestions, I'll need to do some more thinking about this problem. :)
