### ISSUE TITLE
Set size of images

### ISSUE THREAD

**Issue by latot** [teracow/googliser#3]
Hi!, i really like this app (:D), i would like can set the minimum size of the images, i think can be a great feature here, testing little that data is set in the link for example for size >= 720p it add ```&tbs=isz:lt,islt:xga``` to the link.

I think this data can be recollected  from a image test from google, maybe something a miniscript for that?

Thx. Cya.

**Comment by teracow** [comment]
That's a good idea. :)

When I'm next able to continue development, I'd be happy to add this.

For now, the only thing on offer is to exclude images based on file size.

**Comment by latot** [comment]
Maybe some "dev" option to can add some param to the url?, i think can help while some features are incorporated here (like add ```&size=sd```).

**Comment by ghost** [comment]
I agree, an image size filter based in dimensions or resolution would be a great idea. So we could download images by proportions, for example —horizontal or vertical—.

**Comment by teracow** [comment]
Hi guys, thank you for your patience. I'm now returning to develop Googliser and can begin adding this. :)

I've been thinking of a couple of mutually-exclusive parameters where the image dimensions could be specified. Something like:
`--dimensions "1920x1080"` for an exact size, or `--minimum-size "10mp"` to set the minimum size.

Happy for you guys to suggest a better way.

**Comment by latot** [comment]
Hi!, thx.

A little question, google can set the minimum size to '1024x768', or '800x600', etc. How that part will works with mp?

and google can set the images to size 'Big', 'small', etc. maybe include this?

Cya.

**Comment by ghost** [comment]
Great! The Googliser is fantastic, I love it!

I was thinking about checking the format of the images just after downloading each one. Something like download, then check height, check width, bind a «proportions» parameter with = height/width, and if «proportions» < 1 then the image is horizontal, so delete it and search again with another parameters, maybe changing the minimum size.

But of course, if the size can be checked before downloading that would be faster and better.

N.

**Comment by teracow** [comment]
@latot - yes, the size parameter posted is the same as the user selects. So if they want images larger than 20MP (5120 x 3840), then the URL becomes: `&tbs=isz:lt,islt:20mp`

So, I just need to write some validation code for the different variations Google offer here. :)

**Comment by teracow** [comment]
@nikitong - it looks like it is possible to check the image dimensions before downloading, so I'll add that and see if it's faster than waiting for each image to actually download. Aspect ratio is also a good idea. What about a parameter such as `--aspect=landscape` ?

**Comment by latot** [comment]
Hi, just a note, google in advance search we can select the shape of the images.

**Comment by teracow** [comment]
To get the ball rolling on this, I've pushed an early version of the minimum pixel count parameter. 

**Example:** to only download images with more than 2 megapixels, specify with `--minimum-pixels 2mp` 

Valid strings are:
`qsvga|vga|svga|xga|2mp|4mp|6mp|8mp|10mp|12mp|15mp|20mp|40mp|70mp`

Can you guys try it out? 

This is a very early draft and could change at any time. Therefore suggest that - for now - no-one rely on it for production environments, scripts, etc... ;)

**Comment by latot** [comment]
Hi, i test it and works!, i would like recommend two things, if my input is something weird the script skip it, but for example and write wrong the input but i didn't notice it, and without a warning is difficult to know, is possible send it?

And second, i really would like in the help of the script the available strings with the resolution (xga 1024x768 ex).

Thx.

**Comment by teracow** [comment]
@latot - yes, those are things on my to-do list.

**Comment by teracow** [comment]
@latot - Now includes detailed information on the help screen about the minimum pixel count presets, and Googliser won't proceed if an invalid preset is requested. ;)

**Comment by latot** [comment]
Yay! Thx!

**Comment by teracow** [comment]
Also started adding `--aspect-ratio` and had just finished decoding Google's url syntax for multiple advanced settings but ran out of time to add it. I should be able to finish integrating this around 10 hours from now. Stay tuned! ;)

**Comment by teracow** [comment]
Okiedoke, new parameter `--aspect-ratio` is now available. 

**Example:** to download only landscape (wide) images, use `--aspect-ratio w`

Valid strings are:
`t|s|w|xw`

But I think this would be better specified as `tall`, `wide`, etc... by using text instead of shortcodes. I'll work on that this week. 

Next thing to add will be specific image dimensions. Probably only a small number of people would use it, but I think it would be nice to have the option anyway. ;)

**Comment by teracow** [comment]
As the original issue has been resolved, it's time to close this.

Thank you everyone for your contributions and feedback.
