### ISSUE TITLE
Download images, even if there are not enough search hits found

### ISSUE THREAD

**Issue by mfiers** [teracow/googliser#35]
Hey Dan,

I have another suggestion - I commonly run into the problem that googliser does not find sufficient images, and stops with an error message (`!! unable to download enough Google search results`). 

Would it be possible to add the flag to download the images it can find - even if there are not enough? (I hope I'm not overlooking a flag).

Now I rerun the command a few times, until I guestimate the correct number (the number of hits found vary from run to run).

thanks
Mark

**Comment by teracow** [comment]
Hi again Mark. 

Yes, that's a good idea. I'll add a new argument to support this. Any thoughts on a name for this flag?

**Comment by mfiers** [comment]
Thanks! - Not sure about a good flag name. Maybe `--always-download` ? It's a little broad in scope though.

**Comment by teracow** [comment]
This has now been added, but haven't yet pushed it to GitHub as I'm dealing with a montage crash when trying to build a gallery with several hundred images. But I hope to have it all working by the weekend. :)

**Comment by teracow** [comment]
update: Mark, I've just pushed a [commit](https://github.com/teracow/googliser/commit/6c301d1b7e3f3a35638cee17c90e2caf0105b167) to support `--always-download` and solved that montage crash with a local IM configuration change. 

(I needed to update /etc/ImageMagick-6/policy.xml: `<policy domain="resource" name="disk" value="10GiB"/>` )

Can you please try the new option `--always-download` and advise? You may want to allow more failures, so suggest adding `-f0`.

**Comment by mfiers** [comment]
Hey Dan, apologies, was away for a few days.
Update seems to work fine. Thanks!
Mark

**Comment by teracow** [comment]
@mfiers hi Mark, I decided it's a better UX to also allow unlimited failures when using this flag. :)

**Comment by teracow** [comment]
Hi again @mfiers, just a heads-up. I'm planning on removing this as a user-specified option and making it the default behaviour. So, user won't need to specify `--always-download` anymore, as this will always occur. 

The problem for anyone who specifies this option after it's been removed - your googliser will throw an error. You'll need to remove it from any scripts that call googliser. :)
