### ISSUE TITLE
Missing binary getopt for macOS Mojave 

### ISSUE THREAD

**Issue by MBtech** [teracow/googliser#38]
Using googliser on macOS Mojave 10.14.6 gave the following error:
`./googliser.sh: line 3100: /usr/local/Cellar/gnu-getopt/2.34/bin/getopt: No such file or directory`

Had to install the gnu-getopt binary to make it work. 
That step is missing from the setup in the readme so I will do a pull request to add that.

**Comment by teracow** [comment]
Thank you @MBtech, I had only recently removed this as a test install into Catalina showed it was installed by default: https://github.com/teracow/googliser/commit/43ab8f17d271f92aa7f928ce9510b9a9b36a37dd

I guess it's still needed on older macOS versions. 

Cheers!
