### ISSUE TITLE
Automating installation

### ISSUE THREAD

**Issue by MBtech** [teracow/googliser#44]
I have written a script for myself to install OS-specific googliser's dependencies, download googliser, add it to the PATH (so that it is accessible from anywhere) and create an alias 'googliser' for it. 

As as user you would only have to do (at least theoratically):
`curl <url of the install script> && chmod +x install.sh && . install.sh`
and that's it. 

I have tested the script on macOS Mojavae and Ubuntu 18.04.2 LTS but it should work on Debian as well. 

I can do a pull request if that's something you want to add.

**Comment by teracow** [comment]
Sounds like a good idea. If the user clones this repo to their local system, they wouldn't even need to `chmod`. They could then run the installation script to configure their system. :)

**Comment by MBtech** [comment]
Well what I have right now isn't assuming a repo clone. I do prefer this way I think, where they don't need to clone the repo.

**Comment by teracow** [comment]
Hi @MBtech, I had to [disable](https://github.com/teracow/googliser/commit/06618a9daf6a6b86d0c8afd4d6554294a3e82d8f) your new conditional branch at the bottom of the script for now, as I was unable to perform a search. Can you please have a look and revise when ready?

**Comment by teracow** [comment]
Also, are you able to make use of the existing `FindPackageManager()` function?

**Comment by teracow** [comment]
Another thought: can you perform a check for $EUID? If it is 0, then user won't need `sudo` to install extras.

**Comment by teracow** [comment]
I'm intrigued by that lonely `:` in your code. What does that do?

**Comment by MBtech** [comment]
Well I think I might as well have changed the conditionals but it's just the [null utility](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_16).

**Comment by teracow** [comment]
Oh cool. I've learned something new today. :)

**Comment by teracow** [comment]
Just made some minor tweaks: https://github.com/teracow/googliser/commit/46de624f9f5e82fffa9de05fa9e88cbf599861d9

:)

**Comment by teracow** [comment]
Just trying a test `--install` on a new Catalina setup, and I've found a problem.  :(

If `brew` hasn't been installed (and therefore `gnu-getopt` isn't available), googliser can't parse the argument list and determine if user has elected to `--install` or not. 

We might need to add a standalone argument check (so not dependent on `gnu-getopt`) just for `--install`.

@MBtech are you able to investigate? :)

**Comment by teracow** [comment]
Just made a quick alteration so I can test installation into macOS Catalina: https://github.com/teracow/googliser/commit/d2085dab7a24a58b8b7228e901bd75597ce8f1cc

The primary argument parser won't need to check for `--install` anymore.

**Comment by MBtech** [comment]
Ahh fair enough.

**Comment by MBtech** [comment]
Sorry I just check the comment.

**Comment by teracow** [comment]
Another thought: I think we should check the applications used by **googliser** (wget, imagemagick, etc...) are not already installed. Then only install them if required.

**Comment by teracow** [comment]
BTW: is `xcode-select` really needed on Catalina? I did an install a few days ago into Catalina, and ignored the installer for `xcode-select`. Everything else installed fine, and **googliser** worked properly too. 

So, maybe we can do without `xcode-select`? I'm not a daily macOS user so I'm not sure how important it is to have `xcode-select` installed.

**Comment by MBtech** [comment]
Yeah, I was thinking about that too. That instead of trying to install and user getting the message that it is already installed. It can be easily checked if something is installed. I think it worked for you because by default Catalina probably has has `xcode`. I haven't done a fresh MacOS install in a long while though.

**Comment by MBtech** [comment]
`xcode-select` is basically a set of command line tools for Mac. What these tools actually include changes from one OS version to another I think. The list of tools installed can be seen in the directory `/Library/Developer/CommandLineTools/usr/bin/`. I think I added that command because the system complained about them not being installed. Likely, one or more of the utility it provides are necessary. Don't remember which one it was though.

**Comment by teracow** [comment]
> I think I added that command because the system complained about them not being installed. Likely, one or more of the utility it provides are necessary. 

It's been part of the readme for some time. But it's something that was included by one of the previous macOS contributors. :)

**Comment by teracow** [comment]
I'll do some test installs this weekend into macOS 10.13, 10.14 and 10.15, along with Ubuntu 19.10.

**Comment by MBtech** [comment]
> > I think I added that command because the system complained about them not being installed. Likely, one or more of the utility it provides are necessary.
> 
> It's been part of the readme for some time. But it's something that was included by one of the previous macOS contributors. :)

I will uninstall it and see if everything works correctly.

**Comment by teracow** [comment]
I've just tested on the 4 platforms mentioned yesterday, and made some notes in https://github.com/teracow/googliser/blob/master/installation-observations.txt

I've made a [few changes](https://github.com/teracow/googliser/commit/aba94d01428caa74fcd21652f5bacb5f682011ee) on-the-fly as per those notes, and ticked these as fixed in the above mentioned text file. :)

**Comment by MBtech** [comment]
Problem with Catalina is because of default shell being zsh. So we probably just need to tell user not to use zsh. Unless support for zsh should be provided.

**Comment by teracow** [comment]
Agree with supporting ZSH. Is this something you can work on?

**Comment by teracow** [comment]
It would be great if we could have a short copy-paste command to download and install **googliser** at the same time. Off the top-of-my-head, something like:
```
install=yes bash <(curl -skL git.io/googliser.sh)
```
... and we would need googliser.sh to check if `[[ $install = yes ]]` then `InstallGoogliser()`.

**Comment by teracow** [comment]
Well, that turned out to be a little harder than I thought it would. Still not completely happy with the solution, but we can work on improving it. :)

So, the good news is there's now an automated way to download and install googliser.sh as per: https://github.com/teracow/googliser/commit/02e486ac540aa402127935e61a940dd6e58f63e1

**Comment by MBtech** [comment]
> Agree with supporting ZSH. Is this something you can work on?

I will see what can be done about that

**Comment by MBtech** [comment]
Also any particular reason why for linux `wget` is used in the README and it's `curl` for Mac?

**Comment by teracow** [comment]
> Also any particular reason why for linux `wget` is used in the README and it's `curl` for Mac?

No, there should be no preference. 

Oh, unless you mean when installing `brew` via `ruby`. That came from the HomeBrew site - their installation guide uses `curl`, so I guess that's because `curl` is always available in macOS.

**Comment by MBtech** [comment]
Well the README also has `curl` for fetching the googliser script in case of MacOS and `wget` for Linux. I am not sure if `wget` is by default present on a fresh copy of macOS or not.

**Comment by MBtech** [comment]
I suggest that we change the automated install command to 

```bash
$ INSTALL=yes bash <(curl -skL git.io/googliser.sh) && source "$HOME/.bash_profile"
```
So that current terminal also has bash completion. What do you think? I think in that case though user would either need to import `bash_profile` or `zshrc` based on the shell they have.

**Comment by teracow** [comment]
> Well the README also has `curl` for fetching the googliser script in case of MacOS and `wget` for Linux.

Sorry, maybe I'm going blind, but I can't find anything like that in the readme. Are you able to quote the section that says this?

The readme does show usage syntaxes for both `wget` and `curl`, but this is OS independent.

**Comment by MBtech** [comment]
No. you are right. I don't know what I was thinking. My bad.

**Comment by teracow** [comment]
No worries, the readme remains a work-in-progress, it can always be improved-upon. :)

We should probably separate the new 'auto-install' instructions from the old 'download-and-execute' instructions. 

Actually, thinking about it now, we could just use the new auto-installer. If the user wants to examine the source-code (as we all should but don't) for googliser they can read it on GitHub or clone the repo locally and check it out before they run it. 

For everyone else, they can use the auto-installer method.

**Comment by teracow** [comment]
OK, I've removed the notes about the previous download then chmod method of obtaining the script, and we'll just use the new method. 

As you're better with ZSH than I, what do you think of using ZSH instead of BASH just for macOS Catalina? 
```
INSTALL=yes zsh <(wget -qO- git.io/googliser.sh)
```
... or similar?

**Comment by teracow** [comment]
I've just realised we might be heading back round to having a separate installer script again. :D

Which might be OK. It would permit something shorter like:
```
bash <(wget -qO- git.io/install-googliser)
```

**Comment by MBtech** [comment]
> OK, I've removed the notes about the previous download then chmod method of obtaining the script, and we'll just use the new method.
> 
> As you're better with ZSH than I, what do you think of using ZSH instead of BASH just for macOS Catalina?
> 
> ```
> INSTALL=yes zsh <(wget -qO- git.io/googliser.sh)
> ```
> 
> ... or similar?

Honestly never used zsh before this. But I can see if it works fine with that command or something similar

**Comment by MBtech** [comment]
> I've just realised we might be heading back round to having a separate installer script again. :D
> 
> Which might be OK. It would permit something shorter like:
> 
> ```
> bash <(wget -qO- git.io/install-googliser)
> ```

and yes I would agree with that. Because for user it wouldn't really matter anyways what they are downloading. The files are downloaded and after being placed to appropriate directory deleted from user's current directory anyways. 

Plus separating the two things would provide ease of modification as well as reading.

**Comment by teracow** [comment]
> Plus separating the two things would provide ease of modification as well as reading.

If we create a separate auto-install script again, should we keep the current `--install` feature in googliser.sh? 

Maybe we could refactor `--install` to execute the separate auto-install script instead of running duplicate code?

**Comment by MBtech** [comment]
I think users can simply use something like 

`bash <(wget -qO- git.io/install-googliser)` 

That fetches the install script which in turn fetches `googliser.sh` and installs everything before remove all scripts from current directory. No need for the `--install` flag?

**Comment by teracow** [comment]
Cool, can you make this happen? :)

Can we name the installer script with a `.sh` extension? We can adapt the git.io shortcode to not have one.

**Comment by teracow** [comment]
I've just uploaded `install.sh` as a placeholder script. Can you put all the installation code into it please? 

I've just registered the shortcode `git.io/get-googliser`, so we can now use:
```
bash <(wget -qO- git.io/get-googliser)
```
... to run `install.sh`.

**Comment by MBtech** [comment]
Yeah I will do that

**Comment by teracow** [comment]
@MBtech nice job. :)

I've just made a couple of minor tweaks. Main one was that the function was no longer needed in `install.sh`

I'll give it a few runs over the weekend.

**Comment by teracow** [comment]
Can we check that `sudo` is required (and installed) before using it in those three installation operations? 

If the current user has write access to `/usr/local/bin/` and `/etc/bash_completion.d/`, then we won't need `sudo`. 

And `sudo` isn't always installed. So, we'll need to provide some sort of fallback instruction to the user. Maybe advise them as to what is required, and let them work it out. Not sure... @MBtech, what do you think?

**Comment by MBtech** [comment]
Actually I was going to remove the sudo for macOS installation anyways. `/usr/local/bin` is always accessible to the users as far as I know. You don't need privileged access for that. So I think sudo is not needed at all for macOS. Will need to check it though. 

But yes I suppose a fallback can be provided. I will see what can be done about that.

**Comment by teracow** [comment]
Cheers! :)

**Comment by teracow** [comment]
I've altered `install.sh` so the installation experience on Linux is approximately what I'd like to see.  

@MBtech, hope you approve. :nerd_face:

**Comment by teracow** [comment]
Oh, I think I've just worked out why sourcing the bash-completion script isn't working. 

It's because we're running `install.sh` in a sub-shell. So, any variables we change inside that shell won't propagate back into the parent shell. :disappointed: 

So, I guess we can remove the source commands.

**Comment by MBtech** [comment]
Well that's why instead of `source` I was using `. $HOME/.bash_profile` which is supposed to propagate the changes to the parent shell as far as I understand. But perhaps my understanding is incorrect

**Comment by teracow** [comment]
> Well that's why instead of `source` I was using `. $HOME/.bash_profile` which is supposed to propagate the changes to the parent shell as far as I understand.

No, that just re-sources your profile into whichever shell is current when you run it.

If we downloaded and ran `install.sh` "manually", it would work because we'd be running it in the current shell.

But because we download and execute `install.sh` inside a sub-shell, the profile is re-sourced inside that sub-shell, not the parent shell.

**Comment by teracow** [comment]
Hi @MBtech are we able to close this issue now? Thank you.

**Comment by MBtech** [comment]
Yeah I think so
