### ISSUE TITLE
Can set the destination folder

### ISSUE THREAD

**Issue by latot** [teracow/googliser#5]
Hi!, i would like can choose the output folder, at least i can't found any option in the help.

Thx!

**Comment by teracow** [comment]
Ah, that's because it doesn't exist. ;-)

But it's a good idea, so I hope to get some time this weekend to add it. Any ideas for a parameter name? Maybe `--directory`  or `--target` or `--output` ?

**Comment by latot** [comment]
i think i would like ```--output  |  -o```

**Comment by teracow** [comment]
.... and done!  ;-)

Can you try it out and let me know if it works as expected?

**Comment by latot** [comment]
Yay! i little problem:
```
./googliser.sh -p "hi" --minimum-pixels xga -output hi
things and more things, why is working if i already download this?
dir
utput
```

when we use ```-o``` option works fine, but with the complete command is using ```uput``` as folder name, is continuation of ```--output``` without the ```-o```

Thx. Cya.

**Comment by teracow** [comment]
In your example, you've only used a single-hypen but also used the full parameter name. 

When specifying a parameter with a shortcode (single letter), use a single hyphen:
`./googliser.sh -p "hi" --minimum-pixels xga -o hi`

When using the full parameter name use a double-hyphen:
`./googliser.sh -p "hi" --minimum-pixels xga --output hi`

:)

**Comment by latot** [comment]
with full param is working bad..

**Comment by teracow** [comment]
Can you please post the full command string you're using?

**Comment by latot** [comment]
i was writing  bad this ```-output hi```, but is curious this:
```
./googliser.sh -p "hi" -output hi
 googliser.sh - 2017-06-17 PID:[5274]

 !! output directory [utput] already exists ... unable to continue.

 -> All done! (with errors)
```

**Comment by teracow** [comment]
Yes, `-output` is wrong. ;)

Have you deleted the "utput" directory?

**Comment by latot** [comment]
no, that is fine, the curious thing is the script works fine with short params and without spaces, ```-o a``` and ```-oa``` are the same, how don't is documented is curious, maybe add an example in the end of the help text? like:
```
 - Examples:
 $ ./googliser.sh -p "cows"
 $ ./googliser.sh -p"cows"
```

**Comment by teracow** [comment]
Yes, that's how the **getopt** utility works. It's quite clever at parsing parameters, but it does need help when switching from shortcodes to full parameters. 

If you use a parameter that expects a specified option or value such as `--phrase` or `--output`, getopts sees the next word on the line as that value. The next word is separated by a whitespace or other symbol.  

This is similar when you use shortcodes except that it's the word immediately following the option. If you type `-output`, it interprets this as parameter `o` with a value of `utput`. If you type `-pcows`, this is parameter `p` with a value of `cows`.

If you use shortcodes that do not expect an option, you can concatenate them as shown in the readme (e.g. `-cdeghkqsv`). ;)

**Comment by teracow** [comment]
I think we're all good on this one, so I'll close it.

@latot - thanks for your great idea and feedback. :)

**Comment by latot** [comment]
Thx improving this!
