### ISSUE TITLE
incomplete images are ending up in the gallery

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#53]
Edited title as I'm not yet sure why this is happening. 

Test parameters were: `-p cows -DSA -P200 -n1000`

**Comment by teracow** [comment]
Yep, can't duplicate this error now - works fine every time.

I'll keep trying.

**Comment by teracow** [comment]
Still testing... this might be due to my Usenet reader downloading at the same time.

**Comment by teracow** [comment]
It's looking like there may be a bug in the way Wget retries downloads. It's causing the retried file to be appended to the original incomplete file.

**Comment by teracow** [comment]
Just found this on the Wget bugtracker: http://savannah.gnu.org/bugs/index.php?51840

Looks like the same problem. :(

**Comment by teracow** [comment]
Unable to fix this. Wget needs fixing instead. :(

**Comment by MBtech** [comment]
Well why not just rely on curl until the bug is fixed with wget?

**Comment by teracow** [comment]
> Well why not just rely on curl until the bug is fixed with wget?

counter-offer: maybe we should prefer `curl`, only using `wget` as a fall-back (for systems without curl)? This would reduce the likelyhood of this bug messing-up downloaded images.
