### ISSUE TITLE
Original File Names

### ISSUE THREAD

**Issue by gkavaliu** [teracow/googliser#6]
Hello,

I think it would be a great feature if it was possible to save the original file names, Instead of having them all renamed.

Thanks

**Comment by teracow** [comment]
Hi @gkavaliu. 

Unfortunately, it became apparent quite early in development that keeping the original names was going to make management of downloaded files difficult when creating the montage image, so I elected to rename them into the sequential order you see. 

It might also be of limited benefit. Here are some original image file names from a search I've just performed:

> 30769_07_01.jpg
> 12.jpg
> 5.jpg
> 333489-t6.jpg
> 46-250.jpg
> Cjl4-mgWEAEg60k.jpg
> 432.jpg
> 


To change this now would require an extensive rewrite and I can't justify that at present. Sorry. :(

But - if it helps, you could use Googliser with the `--links-only` option to create a link list file, then download these manually.
