### ISSUE TITLE
RFC: considering removing some user options

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#62]
Hey all. :)

~Because it works so well, I've made `--race` a default action for now, and I'm looking at removing it as a user-option. This means image download numbers will nearly always over-run and need to be trimmed back, but it's turned-out to be a really fast way of getting images.~

~Also I'd like to remove `--always-download` and make it the default action.~

And remove any need for the user to specify failure-limits via `--failures`. Unlimited download failures should always be allowed (I can't think of a reason to limit this).

Removing these options will cause a runtime error "invalid arguments" for anyone still using them. 

Thoughts please?

**Comment by teracow** [comment]
https://github.com/teracow/googliser/commit/a84d476053eb6d797bbed77c4544b0f7f748865b

**Comment by teracow** [comment]
https://github.com/teracow/googliser/commit/95b283c469b712a5200d616b6365a9e75ef372c8

**Comment by MBtech** [comment]
I agree with the changes already made and I think removal of failure limit also makes sense. 
I would actually also suggest to make `--no-gallery` default too and instead give the option to create the gallery explicitly because that seems like a use case specific thing.

**Comment by teracow** [comment]
@MBtech agree, I've been considering that too. 

OK, I'll begin working on making galleries optional. :)

**Comment by teracow** [comment]
... and done! https://github.com/teracow/googliser/commit/5cabdc19f05c104764b4441fbaa9e7af0a4123eb

**Comment by MBtech** [comment]
Great!
