### ISSUE TITLE
add a tab-completion script when installing?

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#63]

**Comment by MBtech** [comment]
Never tried to do that so let me look into this

**Comment by teracow** [comment]
Looking good! :)

Can we add support for completing filenames/paths for parameters where these would be supplied as arguments?

**Comment by MBtech** [comment]
Yeah. Let me make a pull request for the automatic install to add the completion script and let's make sure that's working before I add support for paths

**Comment by teracow** [comment]
Also, I'm hoping you'll integrate that completion script into the main script - maybe via EOF?
```
InstallGoogliser()
    {
    ...
    cat > googliser-completion << EOF
#!/usr/bin/env bash
_GoogliserCompletion()
...
complete -F _GoogliserCompletion googliser
EOF
```

**Comment by MBtech** [comment]
Sure

**Comment by MBtech** [comment]
> Looking good! :)
> 
> Can we add support for completing filenames/paths for parameters where these would be supplied as arguments?

I suppose you mean that for the flags for which user needs to supply paths, available paths in the directory should be suggested? Like for `--input-links` filename path completion should be suggested.

**Comment by teracow** [comment]
Correct. :)

**Comment by teracow** [comment]
That looks great. I'm learning something about tab-completion too.  :) 

I'm hoping to try out the install routines on a few different platforms this weekend. 

BTW: what platforms are in-use at your end?

**Comment by teracow** [comment]
Just a thought: maybe we should `mv` instead of `cp` the completion script? 

If we only `cp` then a copy is left behind where it's created.

**Comment by MBtech** [comment]
Yeah I was thinking the same. There is no need of the script once it is moved. But I thought if there are some other changes that should be done, I will make that change along with them. Any other thing that would be nice to have for tab completion. I mean there could be help shown for tab completion like the available options for flags that have preset values.

**Comment by MBtech** [comment]
> That looks great. I'm learning something about tab-completion too. :)
> 
> I'm hoping to try out the install routines on a few different platforms this weekend.
> 
> BTW: what platforms are in-use at your end?

I tried it out on Catalina and on Ubuntu 18.04.2

**Comment by teracow** [comment]
> I mean there could be help shown for tab completion like the available options for flags that have preset values.

Really? I didn't know that. Yes, sounds like a good idea. :)

**Comment by teracow** [comment]
The auto-completion script is working well on everything - except Catalina. 

I get a `command not found` error for `complete`. 

I'm guessing `complete` isn't located in a directory found via $PATH? :(

**Comment by teracow** [comment]
Also tried it on Fedora Workstation 31. Tab-completion didn't work until I logged-out of the terminal, then back in again. Perfectly fine after that. :)

**Comment by MBtech** [comment]
> The auto-completion script is working well on everything - except Catalina.
> 
> I get a `command not found` error for `complete`.
> 
> I'm guessing `complete` isn't located in a directory found via $PATH? :(

So that problem is because in Catalina the default shell is zsh instead of bash. There are ways to make bash completion work with zsh but I haven't tested them.

**Comment by MBtech** [comment]
> Also tried it on Fedora Workstation 31. Tab-completion didn't work until I logged-out of the terminal, then back in again. Perfectly fine after that. :)

Somehow the command to load the completion script isn't working. When a new terminal is opened it works fine because then the completion script is loaded automatically.

**Comment by teracow** [comment]
Thank you @MBtech, the original objective has been achieved. :)
