### ISSUE TITLE
overlay image filenames on thumbs?

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#65]
something like https://stackoverflow.com/a/12754055/6182835

**Comment by MBtech** [comment]
You mean in the gallery image, right?

**Comment by teracow** [comment]
Yes, each gallery thumbnail would have the source filename (or URL index) overlaid.

I'm currently messing-about with this to get a feel for what mods will be required in **googliser**:
```
#!/usr/bin/env bash

for img in google*.jpeg; do
    width=$(identify -format %W ${img})
    height=$(identify -format %H ${img})
    newheight=$((height / 10))
    printf 'name:%s\twidth:%s\theight:%s\tnewheight:%s\n' "$img" "$width" "$height" "$newheight"
    convert -background '#0008' -gravity center -fill white -size ${width}x${newheight} caption:"${img}" "${img}" +swap -gravity south -composite "with-caption-${img}"
done
```

**Comment by teracow** [comment]
An observation: 

**It's slow.** Every image needs to be resized first, then have overlay applied. Else montage can crop image (and the overlaid title) when building gallery. 

Kinda kills the appeal of "speedy" downloading. So I'm not sure it will be worth continuing to develop this. :(

**Comment by teracow** [comment]
Discontinuing this for now but might revisit it again at some point.
