### ISSUE TITLE
macOS all: terminal colours wrong?

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#69]
This one has been bothering me for some time. Googliser colour display on macOS always shows the wrong colours. Example: "google" should appear in the same colours shown on the base Google web search-page. 

After reading a few posts about this, it seems macOS changes the result of colour ANSI codes echoed to the terminal in an effort to make things _"look better"_. 

Is this correct, or is it possible to reliably use colours in a script running in the macOS terminal?

**Comment by teracow** [comment]
Debian 10.2 & Konsole:
![googliser appearance on Debian 10 2](https://user-images.githubusercontent.com/18562540/69472335-91f2a100-0df4-11ea-9499-5ca0fdf174b2.png)

macOS 10.13 High Sierra & Terminal:
![googliser appearance on 10 13 High Sierra](https://user-images.githubusercontent.com/18562540/69472301-011bc580-0df4-11ea-9f4a-880b976d7f5e.png)

macOS 10.14 Mojave & Terminal (dark desktop theme):
![googliser appearance on 10 14 Mojave](https://user-images.githubusercontent.com/18562540/69472304-1264d200-0df4-11ea-90ab-60ebbd386bd8.png)

macOS 10.15 Catalina & Terminal (dark desktop theme):
![googliser appearance on 10 15 Catalina](https://user-images.githubusercontent.com/18562540/69472306-1abd0d00-0df4-11ea-80d6-5edd25af706c.png)

**Comment by MBtech** [comment]
So the colors appear fine in iTerm with dark theme but in terminal they do indeed appear incorrectly with the dark theme.

**Comment by teracow** [comment]
Good work on that colour fix @MBtech. :)
