### ISSUE TITLE
Problem in downloading pictures

### ISSUE THREAD

**Issue by mnarizzano** [teracow/googliser#7]
Dear Teracow,
I could not download any image using the script. I have downloaded the script in July and it was working, then back from holiday it did not work any more.
Even on simple use as 
./googliser.sh --number 2 -p "cows" -d
I can not download any image.
I have attached the debug file for your convenience.
I believe that google has changed its search result page format.
All the best
mn
[debug.txt](https://github.com/teracow/googliser/files/1260574/debug.txt)

**Comment by teracow** [comment]
Hi Massimo,

I'm on holidays myself at the moment, but will investigate this when I return home.

**Comment by mnarizzano** [comment]
Ciao Dan,
Thank you for your answer.
Enjoy you holidays.
best
Massimo

2017-08-29 20:36 GMT+02:00 Dan Cropley <notifications@github.com>:

**Comment by teracow** [comment]
Hi Massimo,

I've just examined the new Google results page code and updated the Googliser PageScraper function. Can you please try it out?

**Comment by mnarizzano** [comment]
Ciao Dan,
thank you for your quick fix.
I have tried a bit and it works.
well done thanks.
bye
mn
