### ISSUE TITLE
macOS Catalina: "terminated" message when finished downloading

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#70]
Only seems to be happening on 10.15:

![catalina error when aborting downloads](https://user-images.githubusercontent.com/18562540/69474010-94f68d00-0e06-11ea-9a9e-ea0a5578a86b.png)

**Comment by teracow** [comment]
I'm guessing Catalina's ZSH handles job kills differently to BASH. Something to research.

**Comment by MBtech** [comment]
I think we might need to make sure that googliser isn't used on zsh. Because zsh also has a problem with bash completion specs. Unless you think support for zsh is important

**Comment by teracow** [comment]
> Because zsh also has a problem with bash completion specs.

Oh, didn't know that. :(

> Unless you think support for zsh is important

I'll leave it upto you. I'm more capable with Linux support. I find the ancient utils offered on macOS rather painful to work with. lol...

The general idea should be to affect the end-user's environment as little as possible. Only install what we need. If ZSH is the native shell, then it would be great to get **googliser** working with it. But if not, then BASH would be the next-best thing.

**Comment by MBtech** [comment]
Well they wouldn't necessarily need to install anything. Bash is still available as far as I know. It's just not the default if you install a fresh copy of Catalina. So they can either change the shell to bash or just start a bash shell. But I will see if bash completion specs can be made to work with zsh. zsh apparently also has a problem with bash style comments with '#'

**Comment by teracow** [comment]
OK, not fixed... still happens occasionally. :(

**Comment by teracow** [comment]
Ugh... this thing is starting to annoy me... works fine while testing, then intermittently fails after I push a commit. I'll keep looking. :)

**Comment by teracow** [comment]
Marking this as fixed for now... unless it occurs again. :)
