### ISSUE TITLE
macOS all: gallery image rendered in black and white?

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#71]
Maybe it's just my VirtualBox installs of macOS, but I've just noticed they appear in black and white. Anyone else seeing this?

**Comment by MBtech** [comment]
Indeed the gallery is in black and white on macOS

**Comment by teracow** [comment]
Arg! The gallery should be (and used to be) in colour. Wonder what's gone wrong?

**Comment by teracow** [comment]
The 3 sub-images (title, thumbnails and background) are rendered in colour. Looks like the switch to black-and-white only happens during the `-composite` operation at the end.

**Comment by teracow** [comment]
This might be relevant: just found that `brew` now installs IM7, whereas my Debian workstation uses IM6. 

There was discussion quite a while back that [alpha-channel handling was going to change with IM7](https://www.imagemagick.org/discourse-server/viewtopic.php?p=84108#p84108) which is where I think things are going wrong. 

So, I just need to work out how to get IM7 installed. :)

**Comment by teracow** [comment]
Just asked about this on the IM forum: http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=37121
