### ISSUE TITLE
advise user of all commands before running them during installation

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#75]
I recently noticed a problem during installation.

The user is shown a command requiring elevated privileges, they are then prompted by the OS to authenticate as SUDO, they enter their password, the command runs -  then the next command that also required sudo can run too because of SUDO-mode caching. This looks a little sneaky, like we didn't disclose everything that would happen before the user typed their password. :(

Maybe we should display all commands first and allow user to review them? If they agree, they can enter their password. If not, installation aborts. 

Something like the method Oracle uses in VirtualBox. Anytime VB needs to perform an operation with elevated privileges, it displays the command it wants to run first.

**Comment by MBtech** [comment]
Yeah I totally agree with you.

**Comment by teracow** [comment]
Mea culpa. I hadn't allowed for SUDO-mode caching. :(

I'll start working on this.
