### ISSUE TITLE
add advanced search feature: region?

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#78]
May require a fair bit of work, and will have limited appeal. Not sure about including this one.

**Comment by MBtech** [comment]
Not sure what you mean by region? Do you mean search on a particular google subdomain? like .es instead of .com?

**Comment by teracow** [comment]
Google offer this under -> Google search page -> Settings -> Advanced search -> region. 

Description is "_Find pages published in a particular region._"

The list appears to be countries. I don't know if they simply filter by TLD country-code though.

**Comment by teracow** [comment]
Closing this for now.
