### ISSUE TITLE
title text (with version and PID) is unreadable on macOS 10.14

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#80]

**Comment by MBtech** [comment]
This problem seems to be only in the light mode

**Comment by teracow** [comment]
Now the problem is that the version and PID strings have the same prominence as the script name.

It would be great if version and PID were just white or light-grey, not bright white. :)

I think we should remove the black background and bright foreground colouring from ver and PID, and just output them as regular text.

**Comment by teracow** [comment]
Maybe I'm over-engineering this. ;)

Can we remove the title colours and just get "googliser.sh" in bold and "ver and pid" plain?

**Comment by teracow** [comment]
Actual title fix was done with: https://github.com/teracow/googliser/commit/31bd86c9674316f91fc698f1158b714a60130a5c
