### ISSUE TITLE
should we install bash-completion in Linux?

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#82]
If we install `brew` into macOS, we can install all the extras we like, as we're not interrupting an environment that was already configured (at least, I _hope_ we're not). 

But Linux is a bit different. Some distro's have bash-completion installed by default, some don't. If it's not installed, I don't think we should be installing it because of the impact it may have on the end-user's setup. They may not want bash-completion, they may have even removed it.  

It's not an essential part of googliser, only a convenience, so I think we should only create `googliser-completion` and move it into the required location if user is already using bash-completion. 

I'm not sure how we should test for that, as I think `complete` is a built-in. Maybe check for the existence of known completion directories? 

Thoughts @MBtech?

**Comment by MBtech** [comment]
We can check that. 
But what if user's distro doesn't have `bash-completion` but user wants it? 
Perhaps we should also ask the user if they want bash completion feature before installing dependencies?

**Comment by teracow** [comment]
> But what if user's distro doesn't have `bash-completion` but user wants it?

Then the user can install it themselves. Trying to figure out how to install just the needed packages is painful enough. :)
