### ISSUE TITLE
RFC: add ability to search Yahoo Images/Bing too?

### ISSUE THREAD

**Issue by teracow** [teracow/googliser#90]
This would expand the number of results available. Duplicate image URLs returned by Google and Yahoo would be reduced to a single URL.

**Comment by teracow** [comment]
Interesting: just noticed this at the bottom of Yahoo Images:

> Powered by Bing™

Maybe we should add Bing instead?

**Comment by teracow** [comment]
[from Wikipedia](https://en.wikipedia.org/wiki/Yahoo!_Search)

> In January 2010, Microsoft announced a deal in which it would take over the functional operation of Yahoo! Search, and set up a joint venture to sell advertising on both Yahoo! Search and Bing known as the Microsoft Search Alliance.

> In April 2015, the Microsoft partnership was modified, now only requiring Bing results on the "majority" of desktop traffic, opening the ability for Yahoo to enter into non-exclusive deals for search services on mobile platforms and the remainder of desktop traffic. The amendment also gives either company the ability to terminate the contract with four months' notice. In October 2015, Yahoo subsequently reached an agreement with Google to provide services to Yahoo Search through the end of 2018, including advertising, search, and image search services.[14][15][16]As of October 2019, Yahoo! Search is once again “powered by Bing”.

**Comment by teracow** [comment]
A quick-and-dirty (i.e. can easily be improved upon) link scraper for Bing image results:
```
cat "$pages_pathfile" \
| sed 's|murl&quot;:&quot;http|\n&|g' \
| sed 's|turl|\n&|g' \
| grep murl \
| sed 's|^murl&quot;:&quot;||' \
| sed '/&amp/d' \
| sed '/^var /d' \
| sed 's|&quot.*||' \
> "$image_links_pathfile"
```

**Comment by MBtech** [comment]
> [from Wikipedia](https://en.wikipedia.org/wiki/Yahoo!_Search)
> 
> > In January 2010, Microsoft announced a deal in which it would take over the functional operation of Yahoo! Search, and set up a joint venture to sell advertising on both Yahoo! Search and Bing known as the Microsoft Search Alliance.
> 
> > In April 2015, the Microsoft partnership was modified, now only requiring Bing results on the "majority" of desktop traffic, opening the ability for Yahoo to enter into non-exclusive deals for search services on mobile platforms and the remainder of desktop traffic. The amendment also gives either company the ability to terminate the contract with four months' notice. In October 2015, Yahoo subsequently reached an agreement with Google to provide services to Yahoo Search through the end of 2018, including advertising, search, and image search services.[14][15][16]As of October 2019, Yahoo! Search is once again “powered by Bing”.

I was familiar with the fact that for a long while Yahoo Search had been powered by Bing (ever since Yahoo's decline) but didn't know they underwent a non-exclusive deal later one.

**Comment by MBtech** [comment]
Adding images through Bing search might be cool. It would be interesting to see how much results differ. I wonder if there is a way to quantify the quality of result from each of the search engine (though that's irrelevant in this case)

**Comment by teracow** [comment]
I'm happy to start adding support for searching Bing, but it will probably happen slowly. I suspect there will be a fair bit of refactoring to deal with differences between Google Images and Bing, and some overlap too.

**Comment by teracow** [comment]
Work on this has begun. :)
